### ISSUE TITLE
Remove button not working

### ISSUE THREAD

**Issue by Zharkan** [garciaalvaro/melonpan-block-post-list#9]
First of all, this is a very nice plugin to chose post so thank you for that.

I have an issue with the remove button, it's not working at all. Can you help me fix it please ?

**Comment by garciaalvaro** [comment]
Hi, thank you.
I am not able to reproduce the bug, could you please let me know:
- which version of WordPress are you using?
- are you using Gutenberg plugin, if so, which version?

**Comment by garciaalvaro** [comment]
I see what you mean and can reproduce it. I'm going to take a closer look.

**Comment by Zharkan** [comment]
I thin I solved it, I opened a PR, thank you so much for all the hard work. I cloned it and customized it for a client that wanted this + i18n integration for his CPTs. It's perfect.

#10

**Comment by garciaalvaro** [comment]
Thank you for opening a PR. Sorry I am bit busy these days, as soon as I can I will confirm it. I will keep this issue open until then.

**Comment by garciaalvaro** [comment]
The PR has been merged, thank you.
